# File: .github/workflows/terraform.yml

on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.GELVADE_DEV }}

    - uses: actions/checkout@main          

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init   
      
    - name: Terraform Plan
      run: terraform plan        