# File: .github/workflows/terraform.yml

on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: windows-latest
    steps:

    - name: "Checkout"
      uses: actions/checkout@main      

    - name: Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.GELVADE_DEV }}
        enable-AzPSSession: true

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.GELVADE_DEV }}      

    - name: Terraform Format
      id: fmt
      run:  terraform fmt -check

    - name: Terraform Init
      id: init
      run: terraform init   
      
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error:  true       

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve      