name: Terraform Plan

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest    
    steps:
    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{ secrets.TF_ARM_CLIENT_SECRET }}
        enable-AzPSSession: true 