# File: .github/workflows/terraform.yml

on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout"
      uses: actions/checkout@main      

    - name: "Terraform Init"
      uses: hashicorp/terraform-github-actions@master
      runs-on:  windows-latest
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: "init"      
        
    - name: "Terraform Plan"
      uses: hashicorp/terraform-github-actions@master
      runs-on:  windows-latest
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: "plan"
        args: '-var="client_secret=${{ secrets.clientSecret }}"'        

    - name: "Terraform Apply"
      uses: hashicorp/terraform-github-actions@master
      runs-on:  windows-latest      
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: "apply"
        args: '-var="client_secret=${{ secrets.clientSecret }}"'  