# File: .github/workflows/terraform.yml

name: 'Terraform'
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2 

    - name: Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.GELVADE_DEV }}
        enable-AzPSSession: true

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.GELVADE_DEV }}      

    - name: Terraform Format
      id: fmt
      run:  terraform fmt -check

    - name: Terraform Init
      id: init
      run: terraform init   
      
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -out=newplan
      continue-on-error:  true       

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve newplan